# Generated by Django 3.2.6 on 2022-01-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobdetails_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='Jobname',
            new_name='jobname',
        ),
    ]
